cprop_hardreg: Use delete_insn_and_edges instead of delete_insn: gcc.dg/pr116053-1.c does 'dg-require-effective-target int128' [PR116053]
Small fix-up for commit r16-7574-g6f777c34c9f221a50d0fc22b70b1cf7dd1fd9101
"cprop_hardreg: Use delete_insn_and_edges instead of delete_insn [PR116053]",
where for certain GCC targets, we see:

    [...]gcc/testsuite/gcc.dg/pr116053-1.c:8:6: error: expected declaration specifiers or '...' before '__int128'

	PR rtl-optimization/116053
	gcc/testsuite/
	* gcc.dg/pr116053-1.c: 'dg-require-effective-target int128'.